# Generated by Django 2.0.8 on 2019-05-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(0, 'low'), (1, 'medium'), (2, 'high')], max_length=200),
        ),
    ]
