# Generated by Django 2.0.8 on 2019-05-15 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urban', '0002_auto_20190515_0441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-priority',)},
        ),
    ]
